name: CI

on:
  push:
    branches: ["main", "renovate/*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno check --unstable main.ts
      - run: deno lint --unstable
        if: always()
